import React from "react";

import {
  AngularjsOriginal,
  BashOriginal,
  COriginal,
  CplusplusOriginal,
  CsharpOriginal,
  DartOriginal,
  DjangoPlain,
  ElectronOriginal,
  ExpressOriginal,
  FastapiOriginal,
  FirebasePlain,
  FlaskOriginal,
  FlutterOriginal,
  JavaOriginal,
  JavascriptOriginal,
  KotlinOriginal,
  LuaOriginal,
  MongodbOriginal,
  MysqlOriginal,
  NextjsOriginal,
  PandasOriginal,
  PhpOriginal,
  PostgresqlOriginal,
  PowershellOriginal,
  PythonOriginal,
  PytorchOriginal,
  QtOriginal,
  ReactOriginal,
  RedisOriginal,
  RubyOriginal,
  RustOriginal,
  ScikitlearnOriginal,
  SpringOriginal,
  SqliteOriginal,
  SvelteOriginal,
  SwiftOriginal,
  TensorflowOriginal,
  TypescriptOriginal,
  VuejsOriginal,
} from "devicons-react";

const iconSize = "24";

export const technologyIconMap: { [key: string]: React.ReactNode } = {
  // Frameworks & Libraries
  "next.js": <NextjsOriginal size={iconSize} />,
  sveltekit: <SvelteOriginal size={iconSize} />,
  django: <DjangoPlain size={iconSize} />,
  "ruby on rails": <RubyOriginal size={iconSize} />,
  react: <ReactOriginal size={iconSize} />,
  "react native": <ReactOriginal size={iconSize} />,
  angular: <AngularjsOriginal size={iconSize} />,
  "vue.js": <VuejsOriginal size={iconSize} />,
  flask: <FlaskOriginal size={iconSize} className="theme-aware-icon" />,
  "express.js": (
    <ExpressOriginal size={iconSize} className="theme-aware-icon" />
  ),
  "spring boot": <SpringOriginal size={iconSize} />,
  flutter: <FlutterOriginal size={iconSize} />,
  tensorflow: <TensorflowOriginal size={iconSize} />,
  pytorch: <PytorchOriginal size={iconSize} />,
  "scikit-learn": <ScikitlearnOriginal size={iconSize} />,
  pandas: <PandasOriginal size={iconSize} />,
  qt: <QtOriginal size={iconSize} />,
  tkinter: <PythonOriginal size={iconSize} />,
  electron: <ElectronOriginal size={iconSize} />,
  fastapi: <FastapiOriginal size={iconSize} />,

  // Languages
  typescript: <TypescriptOriginal size={iconSize} />,
  javascript: <JavascriptOriginal size={iconSize} />,
  python: <PythonOriginal size={iconSize} />,
  ruby: <RubyOriginal size={iconSize} />,
  java: <JavaOriginal size={iconSize} />,
  swift: <SwiftOriginal size={iconSize} />,
  kotlin: <KotlinOriginal size={iconSize} />,
  "c++": <CplusplusOriginal size={iconSize} />,
  c: <COriginal size={iconSize} />,
  dart: <DartOriginal size={iconSize} />,
  lua: <LuaOriginal size={iconSize} />,
  powershell: <PowershellOriginal size={iconSize} />,
  bash: <BashOriginal size={iconSize} />,
  rust: <RustOriginal size={iconSize} />,
  php: <PhpOriginal size={iconSize} />,
  "c#": <CsharpOriginal size={iconSize} />,
  svelte: <SvelteOriginal size={iconSize} />,

  // Databases
  postgresql: <PostgresqlOriginal size={iconSize} />,
  mysql: <MysqlOriginal size={iconSize} />,
  mongodb: <MongodbOriginal size={iconSize} />,
  redis: <RedisOriginal size={iconSize} />,
  sqlite: <SqliteOriginal size={iconSize} />,
  firebase: <FirebasePlain size={iconSize} />,
};
